version: "3.9" ## versão do yml
services: ## definição de serviços
  mongodb:
    image: mongo 4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge
      
  alurabooks:
    image: aluradocker/alura-books:1.0
    container_name: alurabooks
    networks: 
      - compose-bridge
    ports: 
      - 3000:3000
    depends_on:
      - mongodb
      
networks:
  compose-bridge:
   driver: bridge
